// <auto-generated />
namespace Tomahawk.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class neededasecuritystampintheusersaccountseed : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(neededasecuritystampintheusersaccountseed));
        
        string IMigrationMetadata.Id
        {
            get { return "201505041956163_needed a security stamp in the users account seed"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
